# примеры API-запросов

@baseUrl = http://localhost:8000/api
@adminToken = 20ce3600387e3186c26448038303114cf05c13ea
@userToken = 432cce369295b7b2bd8ba5f69c18ca02152a5553

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{adminToken}}

{
  "title": "Шкаф IKEA 9",
  "description": "Срочно очень44"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/16/
Content-Type: application/json
Authorization: Token {{userToken}}

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-10-01
Content-Type: application/json
