# Generated by Django 5.0.7 on 2024-07-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['is_main', 'tag'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
